sudo: required
dist: bionic
language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - cmake
      - netcdf-bin
      - libnetcdf-dev
      - swig3.0
      - lcov
      - libgdal-dev
      - libboost-all-dev
      - libssl-dev

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --remove coverage.info '*/thirdparty/*' --output-file coverage.info # filter thirdparty code
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

script:
  - git submodule init
  - git pull --recurse-submodules
  - mkdir build; cd build; cmake -DCOVERAGE=ON -DBUILD_TESTS=ON -DPYTHON_TESTING=ON ..
  - cd build; make -j 2
  - cd build; CTEST_OUTPUT_ON_FAILURE=1 make test
