sudo: required
dist: trusty
language: cpp
compiler: gcc

before_install:
      - sudo apt-get update  -qq
      - sudo apt-get install -qq libsqlite3-dev libnetcdf-dev python python-dev swig tcl8.5-dev lcov netcdf-bin

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --remove coverage.info '*/thirdparty/*' --output-file coverage.info # filter thirdparty code
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

script:
- mkdir build; cd build; cmake -DCOVERAGE=ON ..
- cd build; make -j 4
- cd build; CTEST_OUTPUT_ON_FAILURE=1 make test
